### ISSUE TITLE
How to import Standard Assets packages by Projeny?

### ISSUE THREAD

**Issue by cutepig49** [modesttree/Projeny#21]
Such as "Characters.unitypackage", "Effects.unitypackage"

**Comment by MegaThorx** [comment]
Well if you habe the .unitypackage you could copy it to the assetstore folder in appdata. I followed the folder structere. Unsure if this is necessary.

There should be a folder for custom packages..

**Comment by svermeulen** [comment]
The standard assets stuff actually makes for a good example of using Projeny, since all the standard asset packages depend on each other in some ways.

So what I did was download the Standard Assets unitypackage files and created Projeny packages for them, each with its own `ProjenyPackage.yaml` file which declares the dependencies it has on the other Standard Asset packages.  I've uploaded this to the [latest release](https://github.com/modesttree/Projeny/releases/tag/v0.3.4) page.

So you can just extract `StandardAssets-Unity5.3.4.zip` into your UnityPackages folder and drag those into your project via the projeny gui
