### ISSUE TITLE
How to add gmcs.rsp and smcs.rsp in assets dir?

### ISSUE THREAD

**Issue by daroubing** [modesttree/Projeny#53]
I'm use EasyMovieTexture,need -unsafe config, gmcs.rsp, smcs.rsp in Asssets root dir.Projeny is auto generate files,I don't know how to put these file in Assets root automatic.

**Comment by svermeulen** [comment]
Yes, these files are a bit problematic with Projeny since project requires everything be in package folders.

The best way I can think to address it is to write your own plugin.  This is an undocumented feature.  If you want to try this though, open up the file `Projeny/Source/prj/plugins/ExamplePlugin.py` then uncomment the python code.  This code will be executed every time you initialize a project.  So you can add gmcs.rsp, etc. automatically here
